# syntax=docker/dockerfile:1.7

FROM python:3.11-slim

ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1 \
    PIP_DISABLE_PIP_VERSION_CHECK=1

WORKDIR /app

COPY requirements.migrate.txt ./

RUN --mount=type=cache,target=/root/.cache/pip,sharing=locked \
    python -m pip install --upgrade pip \
    && python -m pip install --no-compile -r requirements.migrate.txt

COPY alembic.ini ./alembic.ini
COPY alembic ./alembic
COPY app ./app

CMD ["alembic", "-c", "alembic.ini", "upgrade", "head"]
