from __future__ import annotations

from collections.abc import AsyncIterator
from typing import Any, Protocol

from app.domain.jobs import LLMCallJob


class JobStore(Protocol):
    def get_stream_channel(self, job_id: str) -> str: ...

    def get_job_result(self, job_id: str) -> LLMCallJob: ...

    def save_job_payload(self, job: Any, llm_call: LLMCallJob) -> None: ...

    def record_wait_time(self, wait_seconds: float) -> None: ...

    def record_completion_metrics(self, llm_call: LLMCallJob) -> None: ...

    def read_average_wait_time_seconds(self) -> float | None: ...

    def read_average_generation_time_seconds(self) -> float | None: ...

    def append_stream_event(self, job_id: str, payload: dict[str, Any]) -> str: ...

    def is_cancel_requested(self, job_id: str) -> bool: ...

    async def stream_llm_events(
        self,
        job_id: str,
        timeout_seconds: int,
    ) -> AsyncIterator[dict[str, Any]]: ...
