import os

REDIS_URL = os.getenv("REDIS_URL", "redis://127.0.0.1:6379/0")
LLM_QUEUE_NAME = os.getenv("LLM_QUEUE_NAME", "llm")
LLM_QUEUE_TIMEOUT_SECONDS = int(os.getenv("LLM_QUEUE_TIMEOUT_SECONDS", "180"))
LLM_QUEUE_WAIT_TIMEOUT_SECONDS = int(os.getenv("LLM_QUEUE_WAIT_TIMEOUT_SECONDS", "300"))
LLM_GENERATION_TIMEOUT_SECONDS = int(
    os.getenv(
        "LLM_GENERATION_TIMEOUT_SECONDS",
        str(LLM_QUEUE_TIMEOUT_SECONDS),
    )
)
LLM_RESULT_TTL_SECONDS = int(os.getenv("LLM_RESULT_TTL_SECONDS", "300"))
LLM_MAX_QUEUE_SIZE = int(os.getenv("LLM_MAX_QUEUE_SIZE", "100"))
LLM_WORKER_CONCURRENCY = int(os.getenv("LLM_WORKER_CONCURRENCY", "1"))
LLM_JOB_MAX_RETRIES = int(os.getenv("LLM_JOB_MAX_RETRIES", "2"))
LLM_STREAM_CHANNEL_PREFIX = os.getenv("LLM_STREAM_CHANNEL_PREFIX", "llm-stream")
LLM_STATUS_POLL_INTERVAL_SECONDS = float(
    os.getenv(
        "LLM_STATUS_POLL_INTERVAL_SECONDS",
        os.getenv("LLM_QUEUE_POLL_INTERVAL_SECONDS", "0.05"),
    )
)
LLM_STREAM_TIMEOUT_SECONDS = int(
    os.getenv("LLM_STREAM_TIMEOUT_SECONDS", str(LLM_QUEUE_TIMEOUT_SECONDS))
)
